[package]
name = "passwords"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.3.3"
ring = "0.16.20"
thiserror = "1.0.38"
anyhow = "1.0.68"
passwords = "3.1.12"
once_cell = "1.17.0"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
mongodb = "2.1"
bson = { version = "2", features = ["chrono-0_4"] }
tokio = "1.23.1"
serde = "1.0.152"
serde_json = "1.0.91"