# fly.toml app configuration file generated for mapopass-api on 2026-03-31T01:30:11-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mapopass-api'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/v2/generate'

[metrics]
  port = 8000
  path = "/metrics"

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
