name: JS Tests

on:
  workflow_call:

jobs:
  js-tests:
    name: JS Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: passwords/app
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: passwords/app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit
