name: Deploy API

on:
  push:
    branches: [main]
    paths:
      - "passwords/api/**"

jobs:
  deploy:
    name: Deploy API to Fly.io
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: passwords/api
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
